---
- name: Give user1 sudo on Debian03
  ansible.builtin.copy:
    content: |
      user1 ALL=NOPASSWD: ALL
    dest: /etc/sudoers.d/user1
    owner: root
    group: root
    mode: '0440'
  when: '"CZ-debian03" in inventory_hostname'

- name: Fetch user3 Private Key from Debian01
  ansible.builtin.fetch:
    src: '/home/user3/.ssh/id_rsa'
    dest: '{{ role_path }}/files/user3/'
    flat: true
  when: '"CZ-debian01" in inventory_hostname'

- name: Copy user3 Private Key to Debian03
  ansible.builtin.copy:
    src: '{{ role_path }}/files/user3/id_rsa'
    dest: '/home/user3/.ssh/id_rsa'
    owner: 'user3'
    group: 'user3'
    mode: '0600'
  when: '"CZ-debian03" in inventory_hostname'

- name: Special System Block
  when: ludus_linux_user_creation_special_host | bool
  block:
    - name: Identify System Users
      ansible.builtin.find:
        paths: /home
        recurse: false
        file_type: directory
        excludes: 'debian,user3,user4'
      register: users

    - name: Fetch SSH Public Keys
      ansible.builtin.fetch:
        src: '{{ special_user_ssh_keys.path }}/.ssh/id_rsa.pub'
        dest: '{{ role_path }}/files/{{ special_user_ssh_keys.pw_name }}/'
        flat: true
      loop: '{{ users.files }}'
      loop_control:
        loop_var: special_user_ssh_keys

    - name: Add SSH Public Key to Users Authorized Keys on Special Host
      ansible.builtin.copy:
        src: '{{ role_path }}/files/{{ special_user_ssh_keys_copy.pw_name }}/id_rsa.pub'
        dest: '/home/{{ special_user_ssh_keys_copy.pw_name }}/.ssh/authorized_keys'
        owner: '{{ special_user_ssh_keys_copy.pw_name }}'
        group: '{{ special_user_ssh_keys_copy.gr_name }}'
        mode: '0600'
      loop: '{{ users.files }}'
      loop_control:
        loop_var: special_user_ssh_keys_copy

    - name: Create Standard Users on special hosts
      ansible.builtin.user:
        name: user3
        create_home: true
        generate_ssh_key: false
        password: '{{ ludus_linux_user_creation.password }}'
        skeleton: /etc/skel
        shell: /bin/bash

    - name: Create user3 .ssh directory
      ansible.builtin.file:
        path: /home/user3/.ssh
        state: directory
        owner: 'user3'
        group: 'user3'
        mode: '0700'

    - name: Add user3 Public Key to debian4
      ansible.builtin.copy:
        src: '{{ role_path }}/files/user3/id_rsa.pub'
        dest: '/home/user3/.ssh/authorized_keys'
        owner: 'user3'
        group: 'user3'
        mode: '0640'

    - name: Give user3 sudo
      ansible.builtin.copy:
        content: |
          user3 ALL=NOPASSWD: ALL
        dest: /etc/sudoers.d/user3
        owner: root
        group: root
        mode: '0440'

    - name: Check if root SSH Key is present
      ansible.builtin.stat:
        path: /root/.ssh/id_rsa
      register: root_ssh_key

    - name: Create root SSH Key Pair on debian4
      ansible.builtin.command:
        cmd: "ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ''"
      when: not root_ssh_key.stat.exists

    - name: Fetch root SSH Public Keys
      ansible.builtin.fetch:
        src: '/root/.ssh/id_rsa.pub'
        dest: '{{ role_path }}/files/root/'
        flat: true

- name: Add root SSH Public Key to Authorized Keys on Linux Hosts
  ansible.builtin.copy:
    src: '{{ role_path }}/files/root/id_rsa.pub'
    dest: '/root/.ssh/authorized_keys'
    owner: 'root'
    group: 'root'
    mode: '0600'
